name: Build

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:

        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                python-version: [10.x, 11.x, 12.x]
                os: [ubuntu-latest, macOS-latest, windows-latest]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm ci
            - run: npm run build:ci
              env:
                  CI: true
